# Generated by Django 6.1 on 2026-08-18 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("workplaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="workplace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workplaces.workplace",
                verbose_name="Рабочее место",
            ),
        ),
    ]
