# Generated by Django 6.1 on 2026-08-20 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название навыка"),
                ),
                (
                    "skill_type",
                    models.CharField(
                        blank=True,
                        help_text="Например: технический, софт-скилл",
                        max_length=50,
                        verbose_name="Тип навыка",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        help_text="Например: junior, middle, expert",
                        max_length=20,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Например, уровень владения или детали",
                        verbose_name="Описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["surname", "name"],
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Мужской"), ("F", "Женский")],
                max_length=1,
                null=True,
                verbose_name="Пол",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Отчество"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="surname",
            field=models.CharField(
                default="Unknown", max_length=50, verbose_name="Фамилия"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="workplace",
            field=models.CharField(
                default="Unknown", max_length=100, verbose_name="Место работы/отдел"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(max_length=100, verbose_name="Должность"),
        ),
        migrations.CreateModel(
            name="EmployeeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="employee_photos/", verbose_name="Фото"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото сотрудника",
                "verbose_name_plural": "Фото сотрудников",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="employees",
                to="employees.skill",
                verbose_name="Навыки",
            ),
        ),
    ]
