# Generated by Django 6.1 on 2026-08-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_workplace"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название навыка"),
                ),
                (
                    "skill_type",
                    models.CharField(
                        choices=[
                            ("frontend", "Фронтенд"),
                            ("backend", "Бэкенд"),
                            ("testing", "Тестирование"),
                            ("management", "Управление проектами"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип навыка",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ],
                        default=1,
                        verbose_name="Уровень владения",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="employees",
                to="employees.skill",
                verbose_name="Навыки",
            ),
        ),
    ]
