# Generated by Django 6.1 on 2026-08-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_skill_employee_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Мужской"),
                    ("female", "Женский"),
                    ("other", "Другой"),
                ],
                default="other",
                max_length=10,
                verbose_name="Пол",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Отчество"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="surname",
            field=models.CharField(
                default="Unknown", max_length=100, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(max_length=100, verbose_name="Должность"),
        ),
    ]
