# Generated by Django 6.1 on 2026-08-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_workplace_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="hired_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата приёма на работу"
            ),
        ),
    ]
