# Generated by Django 6.1 on 2026-08-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0004_employee_gender_employee_patronymic_employee_surname_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="surname",
            field=models.CharField(blank=True, max_length=100, verbose_name="Фамилия"),
        ),
    ]
